name: python project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install dependences
        run:  pip install -r requirements.txt
      - name: install pytest project
        run:  pip install pytest
      - name: test the code
        run:  pavelzw/pytest-action@v2


